package io.ololo.messenger.models

/**
 * Created by ko3a4ok on 10/18/15.
 */
trait Contacts {
  val CONTACTS = Array(
    "Liu Kang",
    "Johnny Cage",
    "Kano",
    "Raiden",
    "Scorpion",
    "Sonya Blade",
    "Sub-Zero",
    "Goro",
    "Shang Tsung",
    "Reptile",
    "Baraka",
    "Jax",
    "Kitana",
    "Kung Lao",
    "Mileena",
    "Kintaro",
    "Shao Kahn",
    "Jade",
    "Noob Saibot",
    "Smoke",
    "Cyrax",
    "Sektor",
    "Kabal",
    "Nightwolf",
    "Sindel",
    "Sheeva",
    "Stryker",
    "Motaro",
    "Ermac",
    "Rain",
    "Chameleon",
    "Khameleon",
    "Fujin",
    "Jarek",
    "Kai",
    "Reiko",
    "Tanya",
    "Quan Chi",
    "Shinnok",
    "Meat",
    "Blaze",
    "Bo' Rai Cho",
    "Drahmin",
    "Frost",
    "Hsu Hao",
    "Kenshi",
    "Li Mei",
    "Mavado",
    "Mokap",
    "Moloch",
    "Nitara",
    "Sareena",
    "Ashrah",
    "Dairou",
    "Darrius",
    "Havik",
    "Hotaru",
    "Kira",
    "Kobra",
    "Onaga",
    "Shujinko",
    "Daegon",
    "Taven",
    "Skarlet",
    "Tremor",
    "Cassie Cage",
    "D'Vorah",
    "Erron Black",
    "Ferra/Torr",
    "Jacqui Briggs",
    "Kotal Kahn",
    "Kung Jin",
    "Takeda"
  )
}
